plugins:
  - '@semantic-release/github'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/commit-analyzer'
  - - '@semantic-release/exec'
    - prepareCmd: "sed -i -e '/AssemblyVersion/s/>.*</>${nextRelease.version}</' DocfxToAstro/DocfxToAstro.csproj; sed -i -e '/<Version>/s/>.*</>${nextRelease.version}</' DocfxToAstro/DocfxToAstro.csproj"
  - - '@semantic-release/changelog'
    - changelogFile: 'CHANGELOG.md'
  - - '@semantic-release/git'
    - assets:
        - "DocfxToAstro/DocfxToAstro.csproj"
        - "CHANGELOG.md"