name: Publish to NuGet

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
            8
            9

    - name: Pack .NET Tool
      run: |
        dotnet pack DocfxToAstro/DocfxToAstro.csproj -c Release -o tool_output

    - name: Semantic Release
      id: semantic
      uses: cycjimmy/semantic-release-action@v4
      with:
        extra_plugins: |
          @semantic-release/exec
          @semantic-release/changelog
          @semantic-release/git
        branch: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to NuGet
      if: steps.semantic.outputs.new_release_published == 'true'
      run: dotnet nuget push tool_output/*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json -p:AssemblyVersion=${{ steps.semantic.outputs.new_release_version }} -p:Version=${{ steps.semantic.outputs.new_release_version }}